### ISSUE TITLE
Move (back) to synchronous map loading

### ISSUE THREAD

**Issue by springmeyer** [mapbox/tilelive-mapnik#58]
Due to mapnik/mapnik#1459 it is unsafe to load maps asynchronously.

We should no longer default to this behavior, to avoid possible crashes. Normal usage in TileMill usually is not impacted by this problem (though I've seen it frequently when running from the command line) - likely because other moving parts slow down map initialization and lead to the singleton being initialized in time. But, this is not safe going forward. Minor optimizations or other changes like #49 that would lead to more maps being loading more quickly can immediately trigger crashes.

**Comment by rochoa** [comment]
Hey @springmeyer, any plans of making a release with this change? :smile:
