### ISSUE TITLE
autoLoadFonts not using boolean value

### ISSUE THREAD

**Issue by rochoa** [mapbox/tilelive-mapnik#90]
Creating a new MapnikSource with `uri.query.autoLoadFonts = false` will set autoLoadFonts to true due to check against 
https://github.com/mapbox/tilelive-mapnik/blob/master/lib/mapnik_backend.js#L89-L90

I'm just wondering if we could consider taking `uri.query.autoLoadFonts` as boolean?

**Comment by rochoa** [comment]
See https://github.com/CartoDB/tilelive-mapnik/commit/b82b5bdf49dc07c5189ba5010e548e24297da9f9

**Comment by springmeyer** [comment]
Can you give c149910 a try?

**Comment by springmeyer** [comment]
v0.6.15 is published with this fix now.

**Comment by rochoa** [comment]
:+1: Working!

Thanks a lot for the quick response and fix!
